### ISSUE TITLE
Does not support quotes around fields

### ISSUE THREAD

**Issue by SQLGuru** [martindrapeau/csvjson-app#1]
Embedded commas in a quote delimited field does not work.

**Comment by martindrapeau** [comment]
Could you provide an example (the URL of your test)?

**Comment by martindrapeau** [comment]
Just do a save and copy the URL in this issue.

**Comment by JonasClark** [comment]
I had a question about this too - in a few of my CSV fields I had added backslashes to escape double quotations (in my case they were being used frequently in product descriptions to specify inches). The JSON output frequently came out with multiple backslashes  - three in most cases. Was wondering what to do so that I don't have to go through and clean them manually in my MongoDB afterwards? 

Does the converter automatically add backslashes? Was it mistake to add my own, pre-conversion?

Thanks!

**Comment by martindrapeau** [comment]
Hi Jonas,
Could you provide a sample example? Run it through csv2json, save it and
copy the URL here.
Thanks,
--Martin

**Comment by JonasClark** [comment]
Hi Martin - 

Thanks for the response! 

If it's okay I'll just copy it in here: 

CSV Input:

source	source_url	catalog_num	category	listing_num	title	description	price	price_realized	original_date	image_urls					Archive_Year
Martin Keane		91	Bamboo Fly Rod	7	Tim Zietak Quad 6'6\" 2/2 DF	Well known nationally  for his artistic Quad Rods TIM ZIETAK.  We offer this 6 1/2' , 2/2,  light  DF  action;  with  dark  richly  flamed  shafts,  silks  are  dk.  red  with  black tipping & it has a red agate stripping guide & beautifully blued ferrules & cap & band on the fine mahogany reel seat. Tim's rods continue to please & amaze veteran expert fly fishermen;  this little \"sleeper\" awaits your discovery; it's brand  new, unused with a superb varnish finish.  	1350		2006						2006
Martin Keane		91	Bamboo Fly Rod	8	Orvis Caenis 6'9\" 2/2 #4	ORVIS  Caenis  6'9\",  2/2,  absolutely  new  for  #4  line,  cork  seat  with  2  thin  sliding    bands,  2 1/4 oz., chrome  guides,  perfect  ferrule blue, very  handsome  with  new  cond. bag & label on tube, ser. #80,3XX.  	680		2006						2006 

JSON Output:

[
  {
    "source": "Martin Keane",
    "source_url": 0,
    "catalog_num": 91,
    "category": "Bamboo Fly Rod",
    "listing_num": 7,
    "title": "Tim Zietak Quad 6'6\\\" 2/2 DF",
    "description": "Well known nationally  for his artistic Quad Rods TIM ZIETAK.  We offer this 6 1/2' , 2/2,  light  DF  action;  with  dark  richly  flamed  shafts,  silks  are  dk.  red  with  black tipping & it has a red agate stripping guide & beautifully blued ferrules & cap & band on the fine mahogany reel seat. Tim's rods continue to please & amaze veteran expert fly fishermen;  this little \\\"sleeper\\\" awaits your discovery; it's brand  new, unused with a superb varnish finish.",
    "price": 1350,
    "price_realized": 0,
    "original_date": 2006,
    "image_urls": 0,
    "": 0,
    "Archive_Year": 2006
  },
  {
    "source": "Martin Keane",
    "source_url": 0,
    "catalog_num": 91,
    "category": "Bamboo Fly Rod",
    "listing_num": 8,
    "title": "Orvis Caenis 6'9\\\" 2/2 #4",
    "description": "ORVIS  Caenis  6'9\\\",  2/2,  absolutely  new  for  #4  line,  cork  seat  with  2  thin  sliding    bands,  2 1/4 oz., chrome  guides,  perfect  ferrule blue, very  handsome  with  new  cond. bag & label on tube, ser. #80,3XX.",
    "price": 680,
    "price_realized": 0,
    "original_date": 2006,
    "image_urls": 0,
    "": 0,
    "Archive_Year": 2006
  }
]

**Comment by JonasClark** [comment]
PS - interestingly, though the copy above (which was taken directly from the output) shows two backslashes resulting from the CSV, the actual visual display of the output shows three backslashes. I'm stumped as to why that might be the case but I've attached a screenshot in case that's helpful. 

![screenshot 2015-05-27 13 49 42](https://cloud.githubusercontent.com/assets/3719084/7843434/a6892340-0477-11e5-9eaf-1651af377b77.png)

**Comment by martindrapeau** [comment]
For reference, here is the test case.
http://www.csvjson.com/csv2json/d142bb375cd6b9240661ff543e6fcc71

**Comment by JonasClark** [comment]
Duh, gotcha - just saw the "save" button in the upper right! :)

**Comment by JonasClark** [comment]
Hi Martin - just wanted to see if you had any updates about the backslashes in conversion. No pressure, just eager to know! -Jonas

**Comment by martindrapeau** [comment]
Give it a go how. Double quotes should no longer appear.
And I've made changes to support commas in quotes.
