### ISSUE TITLE
sql2json does not support INSERT INTO ... VALUES(a,b), (c,d) syntax

### ISSUE THREAD

**Issue by galz** [martindrapeau/csvjson-app#11]
This came up on [StackOverflow](http://stackoverflow.com/questions/39216133/convert-sql-dump-to-json).

The following syntax for sql2jaon works well and shows both inserted rows:

```sql
CREATE TABLE `geo_tags` (
  `gt_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `gt_page_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`gt_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4507036 DEFAULT CHARSET=binary ROW_FORMAT=DYNAMIC;

INSERT INTO `geo_tags` VALUES (3,487781);
INSERT INTO `geo_tags` VALUES (4,487781);

```

But using a shorter syntax for the INSERT, which is usually used by mysqldump, would only show the first value:

```sql
CREATE TABLE `geo_tags` (
  `gt_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `gt_page_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`gt_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4507036 DEFAULT CHARSET=binary ROW_FORMAT=DYNAMIC;

INSERT INTO `geo_tags` VALUES (3,487781),  (4,487781);
```

**Comment by galz** [comment]
@martindrapeau - and nice work!! Very useful tool :)

**Comment by martindrapeau** [comment]
This format is not currently supported. Good feature request.

**Comment by martindrapeau** [comment]
Fixed. Thanks for reporting. Here is your testcase:
http://www.csvjson.com/sql2json/688575184b1e31c39c1fd8786f0509ec

**Comment by galz** [comment]
@martindrapeau - amazing! Thank you!
