### ISSUE TITLE
List of lists does not beautify correctly, adds additional values

### ISSUE THREAD

**Issue by kashiraja** [martindrapeau/csvjson-app#12]
This should be valid JSON, however:

`{
            "values": [
                   [
                    1,
                    2,
                    [
                        3
                    ],
                    4
                ]
            ]
}
`

Becomes:
`
{
  "values": [
    [
      1,
      2,
      [1, 2, 3],
      4
    ]
  ]
}
`
Notice how the list within the list is expanded from list with 1 item to 3 items.

**Comment by martindrapeau** [comment]
I confirm the bug. This happens when the "Inline short arrays" switch is on.

**Comment by martindrapeau** [comment]
Fixed. I also added a depth option so you can specify when to stop inlining arrays. Here is your testcase fixed:
http://www.csvjson.com/json_beautifier/25620df899fc8321e98a9282ae168186
