### ISSUE TITLE
MySQL to Json Error

### ISSUE THREAD

**Issue by jgrockzz** [martindrapeau/csvjson-app#19]
#### Instructions for filing an issue.

1. http://www.csvjson.com/sql2json/8b71cf1fc48b3c4b0dd5884b2b9be09f
2. I think there is Problem with comma, if we have any comma in our data in data field of database, then it is counting as a new entry in Json, instead of counting entry from comma, do one thing 

count it ' ' with this symbol for MySQL, as this ' ' (quotation mark) symbol separates the entries in MySQL.

**Comment by martindrapeau** [comment]
Duplicate of #25 and fixed.
