### ISSUE TITLE
Support single or double quote around the properties 

### ISSUE THREAD

**Issue by hisabimbola** [martindrapeau/csvjson-app#23]
#### Instructions for filing an issue.

In the *JSON beautifier* app it would be nice if we can set whether to use single or double quote around the properties.

Let me know if this is something you feel you will like to know, I do not mind sending a PR.

**Comment by martindrapeau** [comment]
Be my guest. I will happily review your PR.

**Comment by hisabimbola** [comment]
@martindrapeau here you go #24
