### ISSUE TITLE
Commas within data cannot be parsed properly

### ISSUE THREAD

**Issue by jdserato** [martindrapeau/csvjson-app#25]
#### Instructions for filing an issue.

1. Save your testcase (click on the Save link in CSVJSON menu bar) and copy/paste the URL here.
http://www.csvjson.com/sql2json/fe1b434d7f320cebb4a984583b3b1599
2. Describe your request.
I have commas in my data (CSV) and upon exporting, all data after the comma is lost. Replacing the commas is a big rework and is unconventional.

**Comment by martindrapeau** [comment]
Thanks for reporting. I believe I have a solution for this. I hope to push it soon.

**Comment by martindrapeau** [comment]
Give that a try and let me know if it works as you expect. The text is no longer cut. One thing I would have liked to keep are new line characters. Unfortunately, they are not allowed in JSON. I therefore removed them from the text. Alternatively, I could replace them with html `<br>` tags. Would that make sense?
