### ISSUE TITLE
values is undefined

### ISSUE THREAD

**Issue by lbottoni** [martindrapeau/csvjson-app#26]
DROP TABLE IF EXISTS `shops`;
CREATE TABLE `shops` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `city` varchar(50) DEFAULT NULL,
  `address` varchar(50) DEFAULT NULL,
  `postalcode` varchar(50) DEFAULT NULL,
  `province` varchar(100) DEFAULT NULL,
  `province2` varchar(2) DEFAULT NULL,
  `region` varchar(100) DEFAULT NULL,
  `nation_id` smallint(5) unsigned NOT NULL,
  `logitude` varchar(100) DEFAULT NULL,
  `latitude` varchar(100) DEFAULT NULL,
  `idremote` int(11) DEFAULT NULL,
  `urlremote` varchar(255) DEFAULT NULL,
  `jsondataremote` varchar(255) DEFAULT NULL,
  `typemarket` varchar(255) DEFAULT '' COMMENT 'catena di appartenenza',
  `groupmarket` varchar(255) DEFAULT NULL,
  `logo` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`,`nation_id`),
  UNIQUE KEY `idremote_groupmarket` (`idremote`,`groupmarket`),
  KEY `shop_nation` (`nation_id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2065 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of shops
-- ----------------------------
INSERT INTO `shops` VALUES ('1', 'Carrefour Market', 'BUSTO ARSIZIO', 'Via Duca D\\'Aosta, 19', '21052', null, 'VA', 'Lombardia', '109', '8.854601', '45.616616', '1913817', '/punti-vendita/supermercato-carrefour-market-busto-arsizio-duca-daosta-19', null, 'Carrefour Market', 'carrefour', null, null);

try this!

    TypeError: values[k] is undefined

**Comment by lbottoni** [comment]
**\'** in Via Duca D**\**'Aosta, 19

' with or without not work inside a string

**Comment by martindrapeau** [comment]
Bug confirmed. Need to investigate further. I saved the use case at this URL:
http://www.csvjson.com/sql2json/66ce0b33daa6ea09893962199e60e8f9

**Comment by martindrapeau** [comment]
Bug is fixed.
