### ISSUE TITLE
the converter button is not working

### ISSUE THREAD

**Issue by jenniferstevenson811** [martindrapeau/csvjson-app#32]
#### Instructions for filing an issue.

1. Save your testcase (click on the Save link in CSVJSON menu bar) and copy/paste the URL here.
2. Describe your request.

**Comment by martindrapeau** [comment]
Could you provide more details?

**Comment by jenniferstevenson811** [comment]
I can elaborate better via phone if you have time. I can be reached on the mobile number below.

Thank you,
Jennifer Stevenson
DHS OCIO
202-875-1050

**Comment by martindrapeau** [comment]
A screenshot or URL to saved test case would do.

**Comment by jenniferstevenson811** [comment]
I copied the data into the left section, where is says paste CSv here and then I press convert and it doesn’t work and also the arrow is not working.

[cid:image001.png@01D3A579.99D86D40]
Thank you,
Jennifer Stevenson
DHS OCIO
202-875-1050

**Comment by martindrapeau** [comment]
Hi,

The image was not attached. You can click on the Save button above. Then copy and paste the URL here. It will contain your test case.
![image](https://user-images.githubusercontent.com/104156/36211674-ea942a96-116f-11e8-94ae-69f3a0ac3c50.png)

--Martin

**Comment by jenniferstevenson811** [comment]
I am not sure how to get you a screenshot that you asked for?? I tried copying it into this box. the link below is from me copying and pasting the CSV file to convert. 

http://www.csvjson.com/csv2json

**Comment by jenniferstevenson811** [comment]
I do not see where I can attach  a pic either

**Comment by martindrapeau** [comment]
Maybe Javascript is not enabled in your browser. Could you verify that? 


You can send the image directly in Github. First, open Developer Tools and see if there is an error in the Javascript console (F12 usually opens that). Then click on Print Screen to copy your screen to the clipboard. Then, while editing your message in Github, just do Ctrl+V to paste it.

**Comment by jenniferstevenson811** [comment]
[converter pic.docx](https://github.com/martindrapeau/csvjson-app/files/1724657/converter.pic.docx)

**Comment by martindrapeau** [comment]
Hi again,
Is Javascript turned on? Is there an error in the console? From looking at your screenshot, that may be the problem.
--Martin

**Comment by jenniferstevenson811** [comment]
I am not that technical...hahaha...please walk me through. I do not know about errors in console. I usually copy and paste and convert. ive never had this issue. 
Also, how do I check JavaScript? I am working on my government laptop

**Comment by jenniferstevenson811** [comment]
[converter pic.docx](https://github.com/martindrapeau/csvjson-app/files/1724740/converter.pic.docx)
I hit F12

**Comment by martindrapeau** [comment]
After you hit F12, you need to hit F5 to refresh the page. If there is an error, it will be in the console. If there is no error, then it's probably that Javascript is not enabled. You can verify that using these steps:
https://www.technipages.com/internet-explorer-enabledisable-javascript

**Comment by jenniferstevenson811** [comment]
Hi there,  you are correct. I got an error message, see attachment. I am checking JavaScript now.

[converter pic.docx](https://github.com/martindrapeau/csvjson-app/files/1725251/converter.pic.docx)

**Comment by jenniferstevenson811** [comment]
ok so thank you for the instructions you sent to check javascript. I am not sure if it is enabled or diabled but since I do not have admin rights to my laptop I will need to call the helpdesk to see move furthere with changing the custom levels. see pic- where the custom level is grayed out.
[converter pic.docx](https://github.com/martindrapeau/csvjson-app/files/1725263/converter.pic.docx)

**Comment by jenniferstevenson811** [comment]
Question: in order for me to use this site and to converst CSV files into JSON's I will need to enable javascript?

**Comment by martindrapeau** [comment]
From the screenshot I cannot tell if you have Javascript enabled. Check with your help desk.
Yes, Javascript is required to do the conversion.

**Comment by martindrapeau** [comment]
Hi Jennifer,
I haven't heard news. I assume its resolved.

**Comment by jenniferstevenson811** [comment]
Hi! Yes, it was a Javascript issue on my end. Thank you for following up!

Thank you,
Jennifer Stevenson
DHS OCIO
202-875-1050
