### ISSUE TITLE
CSVJSON is not defined

### ISSUE THREAD

**Issue by feofan-msk** [martindrapeau/csvjson-app#38]
1. https://csvjson.com/csv2json/f61181b1203859a845865ae7d5ec4e41
2. After last update (Mar 31 2018) the app throws "ReferenceError: CSVJSON is not defined" even for the given example

**Comment by gnietof** [comment]
1. https://www.csvjson.com/csv2json/333760ca6b375b905212af9cd75fdb96
2. I am having the same issue than @feofan-msk. This data set was working fine a couple of days ago.

**Comment by martindrapeau** [comment]
@feofan-msk it should now work. Browser caching issue I think. Do a hard refresh and try again. Ctrl + F5.
@gnietof same issue. Will now work. However you have a column header with break lines failing the CSV validation. You can remove those and everything will work fine.
![image](https://user-images.githubusercontent.com/104156/38173266-401e3faa-3589-11e8-85ae-762f88e4d539.png)
