### ISSUE TITLE
Add support for the CSVJSON variant of CSV

### ISSUE THREAD

**Issue by DrorHarari** [martindrapeau/csvjson-app#39]
The CSVJSON format is a variant of the common CSV format (as described in RFC 4180) that removes the ambiguity that afflicts the common CSV format (delimiters, escaping rules, encoding,  etc.) by relying on the rules of the well known JSON format.

The CSVJSON format is described at http://csvjson.org

An example of JSON to CSVJSON conversion is:

> [
  {
    "type": "number",
    "value1": 1,
    "value2": 2
  },
  {
    "type": "boolean",
    "value1": false,
    "value2": true
  },
  {
    "type": "null",
    "value1": null,
    "value2": "non null"
  },
  {
    "type": "array of numbers",
    "value1": [1],
    "value2": [1,2]
  },
  {
    "type": "simple object",
    "value1": {"a": 1},
    "value2": {"a":1, 
"b":2}
  },
  {
    "type": "array mixed objects",
    "value1": [1,null,"ball"],
    "value2": [2,{"a": 10, "b": 20},"cube"] 
  },
  {
    "string": "string with quotes",
    "value1": "a\"b",
    "value2": "alert(\"Hi!\")"
  },
  {
    "string": "string with bell&newlines",
    "value1": "bell is \u0007",
    "value2": "multi\nline\ntext"
  }
]

and the resulting CSVJSON encoded CSV file is:

> "index","value1","value2"
"number",1,2
"boolean,false,true
"null",null,"non null"
"array of numbers",[1],[1,2]
"simple object",{"a": 1},{"a":1, "b":2}
"array mixed objects",[1,null,"ball"],[2,{"a": 10, "b": 20},"cube"]
"string with quotes","a\"b","alert(\"Hi!\")"
"string with bell&newlines","bell is \u0007","multi\nline\ntext"

The conversion is, of course, reversible.

Note that I chose to maintain the whitespaces inside the JSON values - only newlines outside of strings need to be eliminated when converting a JSON value to CSV because CSV lines must not be broken.

The conversion steps are rather simple (can be optimized):

## CSVJSON to JSON
1. Read a line
2. Wrap it with [ and ]
3. Parse it as JSON array 
4. Use the values to create the JSON just like they were parsed from regular CSV

## JSON to CSVJSON
1. Get an object from the array (assuming it is of the type this site supports)
2. Ignore the keys (they should be used for the first line in the CSVJSON)
3. Concatenate the values eliminating whitespacess between the values
4. Write this as a single CSVJSON line

**Comment by martindrapeau** [comment]
Hi Dror,

The problem is that this line is not CSV valid:
```
"array mixed objects",[1,null,"ball"],[2,{"a": 10, "b": 20},"cube"]
```
Arrays and objects should be wrapped in double quotes - because you have nested commas and double quotes. Did you consider that issue?

**Comment by DrorHarari** [comment]
Hi Martin,

Sure I have consider this. The line:

"array mixed objects",[1,null,"ball"],[2,{"a": 10, "b": 20},"cube"]

is not valid in plain old CSV but it is perfectly valid in CSVJSON because
each line in a CSVJSON file is made up of multiple JSON values separated by
commas.

In the case the values are simple (strings, numbers, booleans and even
nulls) the result is something that looks like 'classical' CSV with the
only difference being the semantics of escaping in the string.

To parse CSVJSON files, we read one line at a time, wrap it in [ ] and let
a JSON parser split it into the items. This way we don't need to deal with
commas inside strings, with arrays, objects etc.

Consider a case where you export a table from a Postgres database to a
tbl.csv file. With plain CSV format, you need to worry what to do with
columns that are JSON values - with CSVJSON there is no problem for an item
in a CSV row to be a JSON document.

The approach you initially implemented of making each item a string is also
valid but it is not CSVJSON - it is just regular CSV.

The reason why I came up with CSVJSON was not to allow embedding of JSON
objects in a CSV line, that's a nice benefit but my main reason was to have
the very well defined encoding semantics of JSON (as per json.org) be used
to describe CSV lines (just taking out the [ and ]).

/d

**Comment by martindrapeau** [comment]
Ok, I understand now. I'll have to add a switch to JSON to CSV to output CSVJSON instead of plain old CSV.

Is conversion from CSVJSON back to JSON necessary considering one only needs to wrap each line between square brackets?

**Comment by DrorHarari** [comment]
Well, strictly speaking, you are correct and conversion back to valid a
JSON file amounts to:

 "[" + concatLines("[" + line + "]", ",") + "]"

But another way to look at it is to look at the bi-directional
shape-transformation service your app provides and I think it is clearly
useful also for CSVJSONs so why discriminate? 😎

Thanks a lot,

Dror

**Comment by martindrapeau** [comment]
I will add another tool to handle CSVJSON conversion back to JSON specifically. I feel it would be much better to be separate not to overload the existing CSV to JSON conversion tool.

As I was working on that, a question came to mind about the header row. In CSV, the header rows are keys to values. I imagine the intent is the same here. However, what happens if the first row contains non-string values? JSON states that keys must be strings. Thoughts?

**Comment by DrorHarari** [comment]
Oops, previous one was prematurely sent...

>> However, what happens if the first row contains non-string values? JSON
states that keys must be strings. Thoughts?




On Tue, Apr 3, 2018, 2:36 AM Martin Drapeau <notifications@github.com>
wrote:

> I will add another tool to handle CSVJSON conversion back to JSON
> specifically. I feel it would be much better to be separate not to overload
> the existing CSV to JSON conversion tool.
>
> As I was working on that, a question came to mind about the header row. In
> CSV, the header rows are keys to values. I imagine the intent is the same
> here. However, what happens if the first row contains non-string values?
> JSON states that keys must be strings. Thoughts?
>

The answer is simple. Not all uses of cdvjson necessarily fit your
converter and that sample clearly is one. It is useful in the context of a
general csv where the header could give you a full time definition.

The general case is not supportable, certainly for symmetric bi-directional
conversion.

For that particular case, on the csvjson to json conversion, you can make
the first array item an array with all these header objects - a semi
arbitrary decision but one that makes sense if you pick the object names
from the name property of those header objects.

Again, not general but not any json will convert either....

Thanks

/d

**Comment by martindrapeau** [comment]
To convert CSVJSON data without a header of string values, I've added a fallback to use the column position instead. That should do it I think.
Here is the tool, now officially online:
https://www.csvjson.com/csvjson2json

Please take the time to test it a bit more. And do read the descriptive text below the fold. I can modify it if you have feedback. I can also give you a link to a personal website if you have one.

Finally, the tool can always be improved. If you see a use case not supported, please open a GitHub issue.
