### ISSUE TITLE
CSV parsing should supported nested line breaks

### ISSUE THREAD

**Issue by martindrapeau** [martindrapeau/csvjson-app#40]
Currently, this use case fails:
https://www.csvjson.com/csv2json/8176be8c26c4936b3a3eace16c7a1d6b

Its because of this CSV line which includes a line break:
```
"array mixed objects","[1,null,\"ball\"]","[2,{\"a\":10,\"b\":20},\"cube\"]",
,"a\"b","alert(\"Hi!\")","string with quotes"
,"bell is \u0007","multi
line
text","string with bell&newlines"
```
According to [RFC-4180](https://tools.ietf.org/html/rfc4180) seciton 2.6, this is valid CSV.

**Comment by DrorHarari** [comment]
Right - a CSV line with a real linebreak (\n) is indeed valid according to RFC-4180 but this is one of the cases that cause problems when working with CSVs -- Apache Hadoop, specifically its Hive component is notorious for having issues when the data contains newlines.

If the producer of the CSV file (the program exporting data from a database) uses the CSVJSON variant of CSV then newlines get encoded as \n (according to the JSON string value rules) and thus the line is not broken.

The CSV sample input looks a bit garbled - it should be something like:
```
type,value1,value2
"number",1,2
"boolean",false,true,
"null",null,"non null",
"array of numbers",[1],"[1,2]",0
"simple object",{"a":1},{"a":1,"b":2}
"array mixed objects",[1,null,"ball"],[2,{"a":10,"b":20},"cube"]
"string with quotes","a\"b","alert("Hi!")"
"string with bell&newlines","bell is \u0007","multi\nline\ntext"
```
