### ISSUE TITLE
Convert csv to this JS format grouped by category

### ISSUE THREAD

**Issue by facamach** [martindrapeau/csvjson-app#5]
How to obtain this json format? Thanks in advance
From

`item,Chios,Kos,Lesbos,Samos,Rhodes,Crete,Idomeni,Athens,Diavata,locations
Food services,3515,4641,24550,5060,0,0,67989,39131,0,144886
Water bottles,3624,7709,28753,6194,0,0,76722,95277,28772,247051
"Sleeping bags, mats, and blankets",143,1871,9010,1702,0,0,12653,10465,6331,42175
Hygiene items,1847,4678,25399,3732,0,0,36257,27147,32215,131275
Clothing,0,0,5136,0,0,0,14098,0,250,19484
"Other NFIs (survival kits, backpacks, misc.)",3316,11106,62337,5850,200,242,103978,21703,13302,222034`

to 
`var datasetLineChart = [
{ group: "All", category: 2008, measure: 289309 }, 
{ group: "All", category: 2009, measure: 234998 }, 
{ group: "All", category: 2010, measure: 310900 }, 
{ group: "All", category: 2011, measure: 223900 }, 
{ group: "All", category: 2012, measure: 234500 }, 
{ group: "Sam", category: 2008, measure: 81006.52 }, 
{ group: "Sam", category: 2009, measure: 70499.4 }, 
{ group: "Sam", category: 2010, measure: 96379 }, 
{ group: "Sam", category: 2011, measure: 64931 }, 
{ group: "Sam", category: 2012, measure: 70350 }, ];`

**Comment by martindrapeau** [comment]
You can use [underscore](http://underscorejs.org/) `map`, `reduce` and `each` functions to do that directly in the browser console.

1. Using [CSV to JSON](http://www.csvjson.com/csv2json), convert to JSON.
2. Then press F12 to open developer tools. You will have access to those functions via the `_` namespace. For example:
```
data=[...]; // paste your data here
items=_.map(data, function(o) {
  return o.item;
});
```
Will return all items:
```
["Food services", "Water bottles", "Sleeping bags, mats, and blankets", "Hygiene items", "Clothing", "Other NFIs (survival kits, backpacks, misc.)"]
```
