### ISSUE TITLE
Package as script / function

### ISSUE THREAD

**Issue by leucotic** [martindrapeau/csvjson-app#70]
Is there a way to package this so it can be linked as a script / used as a function in an html page, similar to papa parse?

**Comment by martindrapeau** [comment]
Which tool are you referring to? Data Janitor?

**Comment by leucotic** [comment]
the csv to json parser (https://www.csvjson.com/csv2json)

**Comment by jleaders** [comment]
An npm, or yarn package would be nice

**Comment by martindrapeau** [comment]
npm package now available here: https://www.npmjs.com/package/csvjson-csv2json
Thanks @leucotic and @jleaders for motivating me to finally publish it. Its been long overdue.
