### ISSUE TITLE
Uploading a JSON file for JSON to CSV should load in the JSON text box

### ISSUE THREAD

**Issue by ejaustin** [martindrapeau/csvjson-app#75]
1. Save your testcase (click on the Save link in CSVJSON menu bar) and copy/paste the URL here.
Test case involves file upload. Test file attached

2. Describe your request.
Uploading a JSON file for JSON to CSV should load in the JSON text box. Right now the JSON loads in the result box.

![Screenshot](https://user-images.githubusercontent.com/6558435/59055369-81506d80-884a-11e9-9b38-504734fe007e.png)
[Test JSON (github doesn't support .json)](https://github.com/martindrapeau/csvjson-app/files/3262872/test.txt)

**Comment by martindrapeau** [comment]
This is now fixed. Thanks for reporting.
