### ISSUE TITLE
"Inline short arrays" adjustable length

### ISSUE THREAD

**Issue by galileo-pkm** [martindrapeau/csvjson-app#76]
Could we get a parameter length for this option?
80 characters is kind of short for modern resolutions.

**Comment by joywave** [comment]
This would  be a nice feature to add

**Comment by martindrapeau** [comment]
I've gone ahead and made that width variable. It will detect the width of the textarea and try to fit as long as it can without wrapping. Let me know if that works for you.

**Comment by galileo-pkm** [comment]
Like a charm, thank you.
